apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  namespace: default
spec:
  capacity: 5Gi
  accessModes:
    - ReadWriteOnce
  reclaimPolicy: Recycle
  remote:
    serverIP: 192.168.1.6
    path: /

