apiVersion: v1
kind: Hpa
metadata:
  name: hpa
  namespace: hpa-namespace
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Pod
    metadata:
      name: hpa-pod
      namespace: hpa-namespace
  selector:
      app: hpa-pod-app
  minReplicas: 1
  maxReplicas: 5
  adjustInterval: 10s
  metrics:
    cpuPercent: 0.5
    memoryPercent: 0.6