apiVersion: v1
kind: Service
metadata:
  name: HpaService-clusterIP
  namespace: my-namespace
  labels:
    app: my-app22
  annotations:
    description: "An example service of fileserver and downloader"
spec:
  type: ClusterIP
  ports:
    - port: 7080
      targetPort: 7080
      protocol: TCP
      name: file-service
  selector:
    app: my-app22
  