apiVersion: v1
kind: Service
metadata:
  name: Service-clusterIP
  namespace: hpa-namespace
  labels:
    app: hpa-pod-app
spec:
  type: ClusterIP
  ports:
    - port: 7080
      targetPort: 7080
      protocol: TCP
      name: file-service
  selector:
    app: hpa-pod-app
  