apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  namespace: default
  labels:
    app: myapplication
  annotations:
    description: "An example pod"
spec:
  volumes:
    - name: example-volume
      emptyDir: {}
  containers:
    - name: example-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/var/www/html"
          name: example-volume
  restartPolicy: Always
  nodeSelector:
    disktype: ssd
