apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: default
  labels:
    app: my-app
  annotations:
    description: "An example deployment of fileserver and downloader"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec: 
      volumes:
        - name: files-volume
          emptyDir: {}
      containers:
        - name: fileserve  
          image: 7143192/fileserver:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: files-volume
              mountPath: "/usr/share/files"
          resources:
            request:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 258Mi
          
        - name: downloader
          image: 7143192/downloader:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: files-volume
              mountPath: "/data"

