apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  namespace: default
  labels:
    app: myapplication
  annotations:
    description: "An example pod of fileserver and downloader"
spec:
  volumes:
    - name: files-volume
      emptyDir: {}
  containers:
    - name: fileserver
      image: fileserver:latest
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: files-volume
          mountPath: "/usr/share/files"
          
    - name: downloader
      image: downloader:latest
      ports:
        - containerPort: 3000
      volumeMounts:
        - name: files-volume
          mountPath: "/data"
  restartPolicy: Always
