apiVersion: v1
kind: Hpa
metadata:
  name: my-hpa
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Pod
    metadata:
      name: my-pod
      namespace: my-namespace
  selector:
      app: my-app11
  minReplicas: 1
  maxReplicas: 20
  adjustInterval: 30s
  metrics:
    cpuPercent: 0.5
    memoryPercent: 0.6