apiVersion: v1
kind: Pod
metadata:
  name: monitor_pod
  namespace: default
  labels:
    app: my-app
  annotations:
    description: "An example pod of fileserver and downloader"
spec:
  volumes:
    - name: monitor-volume
      volumeSource:
        path: "/root/minik8s/examples/"
        type: "Directory"
  containers:
    - name: monitor-server
      image: python:3.8-alpine
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash", "-c", "python /mnt/monitor.py"]
      workingDir: "/mnt"
      volumeMounts:
        - name: monitor-volume
          mountPath: "/mnt"
      mounts:
        - name: monitor-volume
          hostPath: "/root/minik8s/examples/"
          containerPath: "/mnt"
          readOnly: false
      ports:
        - containerPort: 9290
        - hostPort: 9290
        - metrics: "metrics"
  restartPolicy: Always

