apiVersion: v1
kind: Pod
metadata:
  name: network-pod
  namespace: default
  labels:
    app: normal-app
  annotations:
    description: "An example pod of fileserver and downloader"
spec:
  containers:
    - name: fileserver
      image: 7143192/fileserver:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000
          targetPort: 8000
