apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  remote:
    path: /
    server: 172.17.0.2
