apiVersion: v1
kind: Pod
metadata:
  name: test-intercontainer-communication
  namespace: default
  annotations:
    description: "An example pod of server and client"
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
  containers:
    - name: server-container
      image: nginx # 使用nginx作为示例服务器，你可以根据需要替换为其他镜像
      ports:
        - containerPort: 80 # 服务器容器监听的端口
      volumeMounts:
        - name: shared-volume
          mountPath: /shared-volume

    - name: client-container
      image: busybox # 使用busybox作为示例客户端，因为它提供了基本的网络工具
      command:
        [
          "/bin/sh",
          "-c",
          "for i in $(seq 1 10); do wget -qO- http://localhost:80 && break || sleep 5; done; echo $? > /shared-volume/result.txt",
        ]
      volumeMounts:
        - name: shared-volume
          mountPath: /shared-volume
