apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
  namespace: default
spec:
  volumes:
    - name: persistent-volume
      persistentVolumeClaim:
        claimName: pvc
        readOnly: false
  containers:
    - name: pv-container
      image: python:3.7-alpine
      command: ["/bin/sh", "-c", "mkdir test && echo \"Hello World!\" > example.txt && sleep 3600"]
      workingDir: /mnt
      volumeMounts:
        - name: persistent-volume
          mountPath: /mnt
          readOnly: false

