apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: my-namespace
  labels:
    app: my-app11
spec:
  containers:
    - name: fileserver
      image: 7143192/fileserver:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080