apiVersion: v1
kind: ReplicaSet
metadata:
  name: pod-replica
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    app: my-app
  template:
    metadata:
      name: my-app-pod
      namespace: default
      labels:
        app: my-app
    spec:
      containers:
        - name: webserver
          image: jackhel0/httpserver:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "POD_IP=$(hostname -i) &&
            echo \"Running HTTP server on $POD_IP\" &&
            python server.py"]
          ports:
            - containerPort: 7080
            - hostPort: 7080