apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: default
  labels:
    app: my-app
  annotations:
    description: "An example service of fileserver and downloader"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: file-service
  selector:
    app: my-app
  