apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  namespace: default
  labels:
    app: my-app
  annotations:
    description: "An example pod of webserver and downloader"
spec:
  volumes:
    - name: files-volume
      emptyDir:
        sizeLimit: 1Gi
  containers:
    - name: downloader
      image: 7143192/downloader:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
        - hostPort: 3000
      volumeMounts:
        - name: files-volume
          mountPath: "/usr/share/files"

    - name: webserver
      image: python:3.7-alpine
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "python -m http.server 7080"]
      ports:
        - containerPort: 7080
          hostPort: 7080
      volumeMounts:
        - name: files-volume
          mountPath: "/data"
  restartPolicy: Always

