apiVersion: v1
kind: ReplicaSet
metadata:
  name: replica-distribute
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    app: replica-distribute-app
  template:
    metadata:
      name: replica-distribute-app-pod
      namespace: default
      labels:
        app: replica-distribute-app
    spec:
      containers:
        - name: webserver
          image: jackhel0/httpserver:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "export IFCONFIG_RESULT=$(ifconfig) &&
          echo -e \"The ifconfig result is: $IFCONFIG_RESULT\" && python server.py"]
          ports:
            - containerPort: 7080
            - hostPort: 7080