apiVersion: v1
kind: ReplicaSet
metadata:
  name: replica
  namespace: replica-namespace
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    app: replica-app
  template:
    metadata:
      name: replica-app-pod
      namespace: replica-app-pod-namespace
      labels:
        app: replica-app
    spec:
      containers:
        - name: fileserver
          image: 7143192/fileserver:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080