apiVersion: v1
kind: Service
metadata:
  name: replicaService-clusterIP
  namespace: default
  labels:
    app: my-app
spec:
  type: ClusterIP
  ports:
    - port: 7080
      targetPort: 7080
      protocol: TCP
      name: file-service
  selector:
    app: my-app
  