apiVersion: v1
kind: Pod
metadata:
  name: service-web-pod
  namespace: default
  labels:
    app: my-app
  annotations:
    description: "An example pod of fileserver and downloader"
spec:
  containers:
    - name: webserver
      image: python:3.7-alpine
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "python -m http.server 7080"]
      ports:
        - containerPort: 7080
          hostPort: 7080
  restartPolicy: Always

