apiVersion: v1
kind: Pod
metadata:
  name: service_pod2
  namespace: default
  labels:
    app: his-app
  annotations:
    description: "An example pod of fileserver and downloader"
spec:
  containers:
    - name: monitor-server
      image: python:3.9-slim
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", " echo 'nameserver 223.5.5.5' >  /etc/resolv.conf && python -m pip install --upgrade pip && pip install prometheus_client && python /mnt/monitor.py"]
      workingDir: "/mnt"
      mounts:
        - hostPath: "/root/minik8s/examples"
          containerPath: "/mnt"
          readOnly: false
      ports:
        - containerPort: 9876
          hostPort: 9876
  restartPolicy: Always

