apiVersion: v1
kind: Service
metadata:
  name: myservice-nodeport
  namespace: default
  labels:
    app: my-app
  annotations:
    description: "An example service of fileserver and downloader"
spec:
  type: NodePort
  ports:
    - port: 7080
      targetPort: 7080
      nodePort: 10000
      protocol: TCP
      name: file-service
  selector:
    app: my-app
  