apiVersion: v1
kind: Service
metadata:
  name: myservice-clusterIP2
  namespace: default
  labels:
    app: his-app
  annotations:
    description: "An example service of service"
spec:
  type: ClusterIP
  ports:
    - port: 9876
      targetPort: 9876
      protocol: TCP
      name: file-service
  selector:
    app: his-app
  