apiVersion: v1
kind: Pod
metadata:
  name: dns_nginx
  labels:
    dns: nginx
spec:
  volumes:
    - name: dns-pvc-volume
      persistentVolumeClaim:
        claimName: my-dns
        readOnly: false
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
      - name: dns-pvc-volume
        mountPath: /mnt
    ports:
    - containerPort: 80
   