# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "feature/*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'

      - name: Format check
        run: |
          FORMATTING_ISSUES=$(gofmt -l .)
          if [ -n "$FORMATTING_ISSUES" ]; then
            echo "Warning: The following files have formatting issues and should be fixed:"
            echo "$FORMATTING_ISSUES"
          else
            echo "Code formatting check passed."
          fi

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
